on:
  repository_dispatch:
    types:
      - resource-published
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://gd.headwire.workers.dev/webhook'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.GD_TOKEN }}"}'
          data: '${{ github.event.client_payload }}'
